// ─────────────────────────────────────────────────────────────────────────────
// firebase_options.dart
//
// Normally generated by `flutterfire configure`, but hand-authored here from the
// Firebase Console web config. Only the WEB entry is needed: mobile keeps using
// google-services.json / GoogleService-Info.plist via the bare
// `Firebase.initializeApp()` call, and main.dart only reads
// DefaultFirebaseOptions.currentPlatform inside `if (kIsWeb)`.
//
// 1. Firebase Console → Project settings → General → Your apps → Web app.
// 2. Replace each REPLACE_… below with the matching firebaseConfig value.
//    (measurementId is optional — delete the line if your project has none.)
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  /// Returns the options for the platform the app is running on.
  /// Only web is wired up here on purpose (see header).
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError(
      'DefaultFirebaseOptions are only configured for web. On mobile, '
          'Firebase.initializeApp() reads the native config file instead.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRirfv947dPnfZeJg2zsvx86lfD41aM8I',
    authDomain: 'everywhere-9278c.firebaseapp.com',          // e.g. your-project.firebaseapp.com
    databaseURL: 'https://everywhere-9278c-default-rtdb.europe-west1.firebasedatabase.app',
    projectId: 'everywhere-9278c',
    storageBucket: 'everywhere-9278c.firebasestorage.app',    // e.g. your-project.appspot.com
    messagingSenderId: '1030362853538',
    appId: '1:1030362853538:web:a8c970f3ede1edd273e7fb',                // the web appId: 1:...:web:...
    measurementId: 'G-77MH21E76P',    // optional — delete if absent
  );
}