import 'package:everywhere/components/formatters.dart';
import 'package:everywhere/models/notification_model.dart';
import 'package:everywhere/providers/user_provider.dart';
import 'package:everywhere/services/api_service.dart';
import 'package:everywhere/services/session_service.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hive_flutter/adapters.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'app.dart';
import 'core/auth/auth_provider.dart';
import 'features/communication/providers/sync_contact_provider.dart';
import 'package:flutter_ios_preview/flutter_ios_preview.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:firebase_app_check/firebase_app_check.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` (see notes)

void main() async {


// AFTER
  WidgetsFlutterBinding.ensureInitialized();

  // Web needs explicit options (no google-services.json on web); mobile keeps
  // reading its native config file.
  if (kIsWeb) {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  } else {
    await Firebase.initializeApp();
  }

  // App Check: debug provider on Android. Skip on web for now — it would need a
// reCAPTCHA v3 site key, and the public web reads don't require App Check.
  if (!kIsWeb) {
    await FirebaseAppCheck.instance.activate(
      androidProvider: AndroidProvider.debug,
    );
  }

  // await FirebaseAppCheck.instance.activate(
  //   androidProvider: AndroidProvider.debug,
  //   // App Check on web uses reCAPTCHA v3, not the debug provider.
  //   webProvider: kIsWeb
  //       ? ReCaptchaV3Provider('REPLACE_WITH_RECAPTCHA_V3_SITE_KEY')
  //       : null,
  // );
  
  await Hive.initFlutter();

  final prefs = await SharedPreferences.getInstance();
  final isGuest = prefs.getBool('isGuest') ?? false;

  await AppLinkHandler.init();

  Hive.registerAdapter(AppNotificationAdapter());
  await Hive.openBox<AppNotification>('notifications');

  SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.transparent
      ));
  runApp(
      MultiProvider(
        providers: [
          ChangeNotifierProvider(
              create: (_) => SessionProvider()),
          ChangeNotifierProvider(
              create: (_) => SyncContactProvider()),
          ChangeNotifierProvider(
              create: (_) => AuthProvider(api: ApiService(), initialGuest: isGuest,)),
          ChangeNotifierProvider(
            create: (_) => UserProvider(api: ApiService())..initIfAuthenticated(),
          ),

        ],
        child: IosPreview(
          deviceModel: DeviceModel.iPhone16ProMax,
            enableInspector: false,
            useFrame: false,
            child:  MyApp()),)
  );
}



