import 'package:everywhere/components/formatters.dart';
import 'package:everywhere/models/notification_model.dart';
import 'package:everywhere/providers/user_provider.dart';
import 'package:everywhere/services/api_service.dart';
import 'package:everywhere/services/session_service.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hive_flutter/adapters.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'app.dart';
import 'core/auth/auth_provider.dart' show AuthProvider;
import 'features/communication/providers/sync_contact_provider.dart';
import 'package:flutter_ios_preview/flutter_ios_preview.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:firebase_app_check/firebase_app_check.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` (see notes)
// add imports
import 'package:app_links/app_links.dart';
import 'package:firebase_auth/firebase_auth.dart' hide AuthProvider;
import 'core/router/app_router.dart' show bootDeepLinkLocation;

void main() async {


// AFTER
  WidgetsFlutterBinding.ensureInitialized();

  // Web needs explicit options (no google-services.json on web); mobile keeps
  // reading its native config file.
  if (kIsWeb) {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  } else {
    await Firebase.initializeApp();
  }

  // App Check: debug provider on Android. Skip on web for now — it would need a
// reCAPTCHA v3 site key, and the public web reads don't require App Check.
  if (!kIsWeb) {
    await FirebaseAppCheck.instance.activate(
      androidProvider: AndroidProvider.debug,
    );
  }

  // await FirebaseAppCheck.instance.activate(
  //   androidProvider: AndroidProvider.debug,
  //   // App Check on web uses reCAPTCHA v3, not the debug provider.
  //   webProvider: kIsWeb
  //       ? ReCaptchaV3Provider('REPLACE_WITH_RECAPTCHA_V3_SITE_KEY')
  //       : null,
  // );
  
  await Hive.initFlutter();

  final prefs = await SharedPreferences.getInstance();
  final isGuest = prefs.getBool('isGuest') ?? false;

  await AppLinkHandler.init();

  // Cold-start deep link (app launched by tapping an amril.app link).
  const ownHosts = {'amril.app', 'www.amril.app'};
  final bootUri = await AppLinks().getInitialLink();
  final launchedFromLink = bootUri != null && ownHosts.contains(bootUri.host);
  if (launchedFromLink) {
    bootDeepLinkLocation =
    bootUri.hasQuery ? '${bootUri.path}?${bootUri.query}' : bootUri.path;
  }
  // Treat a logged-out link-visitor as a guest so the router shows the content
  // instead of welcome. (continueAsGuest persists this on first real action;
  // here we just seed AuthProvider's initial state for the first frame.)
  final bootGuest =
      isGuest || (launchedFromLink && FirebaseAuth.instance.currentUser == null);

  if (launchedFromLink && bootGuest) await prefs.setBool('isGuest', true);

  Hive.registerAdapter(AppNotificationAdapter());
  await Hive.openBox<AppNotification>('notifications');

  SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.transparent
      ));
  runApp(
      MultiProvider(
        providers: [
          ChangeNotifierProvider(
              create: (_) => SessionProvider()),
          ChangeNotifierProvider(
              create: (_) => SyncContactProvider()),
          ChangeNotifierProvider(
              create: (_) => AuthProvider(api: ApiService(), initialGuest: bootGuest,)),
          ChangeNotifierProvider(
            create: (_) => UserProvider(api: ApiService())..initIfAuthenticated(),
          ),

        ],
        child: IosPreview(
          deviceModel: DeviceModel.iPhone16ProMax,
            enableInspector: false,
            useFrame: false,
            child:  MyApp()),)
  );
}



