import 'package:everywhere/components/formatters.dart';
import 'package:everywhere/models/notification_model.dart';
import 'package:everywhere/features/communication/services/chat_cache_service.dart';
import 'package:everywhere/providers/user_provider.dart';
import 'package:everywhere/services/api_service.dart';
import 'package:everywhere/services/session_service.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:hive_flutter/adapters.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'app.dart';
import 'core/analytics/analytics.dart';
import 'core/auth/auth_provider.dart' show AuthProvider;
import 'core/region/region_provider.dart';
import 'features/communication/providers/sync_contact_provider.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:firebase_app_check/firebase_app_check.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` (see notes)
import 'package:app_links/app_links.dart';
import 'package:firebase_auth/firebase_auth.dart' hide AuthProvider;
import 'core/router/app_router.dart' show bootDeepLinkLocation;
import 'package:flutter_web_plugins/url_strategy.dart';

void main() async {


// AFTER
  WidgetsFlutterBinding.ensureInitialized();

  // main.dart — import:


// in main(), right after WidgetsFlutterBinding.ensureInitialized():
  if (kIsWeb) usePathUrlStrategy();

  // Web needs explicit options (no google-services.json on web); mobile keeps
  // reading its native config file.
  if (kIsWeb) {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  } else {
    await Firebase.initializeApp();
  }

  // PHASE 9 — analytics. Safe no-op if Analytics is unavailable.
  Analytics.I.init();

  // App Check: debug provider on Android. Skip on web for now — it would need a
// reCAPTCHA v3 site key, and the public web reads don't require App Check.
  if (!kIsWeb) {
    await FirebaseAppCheck.instance.activate(
      androidProvider: AndroidProvider.debug,
    );
  }

  // await FirebaseAppCheck.instance.activate(
  //   androidProvider: AndroidProvider.debug,
  //   // App Check on web uses reCAPTCHA v3, not the debug provider.
  //   webProvider: kIsWeb
  //       ? ReCaptchaV3Provider('REPLACE_WITH_RECAPTCHA_V3_SITE_KEY')
  //       : null,
  // );
  
  await Hive.initFlutter();

  final prefs = await SharedPreferences.getInstance();
  final isGuest = prefs.getBool('isGuest') ?? false;

  // PHASE 9 — region flag, read synchronously so the first frame gates
  // correctly with zero flicker. Fresh installs default to NG (pre-Phase-9
  // behavior); the value self-corrects after the first /users/me sync.
  final initialIsNgTied =
      (prefs.getString(RegionProvider.prefsKey) ?? 'NG') == 'NG';

  await AppLinkHandler.init();

  // // Cold-start deep link (app launched by tapping an amril.app link).
  // const ownHosts = {'amril.app', 'www.amril.app'};
  //
  // final bootUri = await AppLinks().getInitialLink();
  // final launchedFromLink = bootUri != null && ownHosts.contains(bootUri.host);

  // main.dart — wrap the existing cold-start App-Link block:
  bool launchedFromLink = false;
  if (!kIsWeb) {                                   // ← App Links are mobile-only
    const ownHosts = {'amril.app', 'www.amril.app'};
    final bootUri = await AppLinks().getInitialLink();
    launchedFromLink = bootUri != null && ownHosts.contains(bootUri.host);
    if (launchedFromLink) {
      bootDeepLinkLocation =
      bootUri.hasQuery ? '${bootUri.path}?${bootUri.query}' : bootUri.path;
    }
  }
  final bootGuest =
      isGuest || (launchedFromLink && FirebaseAuth.instance.currentUser == null);

  // if (launchedFromLink) {
  //   bootDeepLinkLocation =
  //   bootUri.hasQuery ? '${bootUri.path}?${bootUri.query}' : bootUri.path;
  // }
  // // Treat a logged-out link-visitor as a guest so the router shows the content
  // // instead of welcome. (continueAsGuest persists this on first real action;
  // // here we just seed AuthProvider's initial state for the first frame.)
  // final bootGuest =
  //     isGuest || (launchedFromLink && FirebaseAuth.instance.currentUser == null);

  if (launchedFromLink && bootGuest) await prefs.setBool('isGuest', true);

  Hive.registerAdapter(AppNotificationAdapter());
  await Hive.openBox<AppNotification>('notifications');

  // Phase 3 — local-first chat cache (instant load + offline history that
  // survives server-side message expiry/cleanup).
  await ChatCacheService.instance.init();

  SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.transparent
      ));
  // Flutter 3.27+ defaults to SystemUiMode.edgeToEdge which disables
  // adjustResize. This reverts to classic mode so the window shrinks
  // when the keyboard opens and every TextField rises automatically.
  // Safe on targetSdk=34; only targetSdk>=35 force-enables edge-to-edge.
  await SystemChrome.setEnabledSystemUIMode(
    SystemUiMode.manual,
    overlays: SystemUiOverlay.values,
  );

  // After Firebase.initializeApp() / AppCheck.activate():
// Firebase restores a persisted session asynchronously (on web, currentUser is
// null until IndexedDB hydrates). Wait for the first auth event so the first
// route decision + initIfAuthenticated() see the real user, not "logged out".
  try {
    await FirebaseAuth.instance
        .authStateChanges()
        .first
        .timeout(const Duration(seconds: 3));
  } catch (_) {/* no session / slow net — proceed as logged-out */}

  runApp(
      MultiProvider(
        providers: [
          ChangeNotifierProvider(
              create: (_) => SessionProvider()),
          ChangeNotifierProvider(
              create: (_) => SyncContactProvider()),
          ChangeNotifierProvider(
              create: (_) => AuthProvider(api: ApiService(), initialGuest: bootGuest,)),
          ChangeNotifierProvider(
            create: (_) => UserProvider(api: ApiService())..initIfAuthenticated(),
          ),

          // PHASE 9 — region gate. Re-evaluates on every UserProvider update,
          // so login, /users/me refresh, and Home-country changes all flow
          // through automatically.
          ChangeNotifierProxyProvider<UserProvider, RegionProvider>(
            create: (_) => RegionProvider(initialIsNgTied: initialIsNgTied),
            update: (_, userProv, region) => region!..syncFromUser(userProv.user),
          ),

        ],
          child:  MyApp()
      ),
  );
}



