// lib/features/legal/legal_docs.dart
//
// Single registry of Amril's legal documents for the app side.
// The HTML *content* for each lives in assets/legal/<slug>.html (generated by
// build_legal.py — the same source that produces the public /legal/<slug>
// web pages, so in-app and web never drift). This file only describes which
// documents exist and how to label them, so the Settings hub, deep links, and
// any "you must accept" flows all read from one place.

import 'package:flutter/material.dart';

/// One legal document: its asset, its human title, and the icon used in lists.
class LegalDoc {
  final String slug; // matches assets/legal/<slug>.html AND /legal/<slug> on web
  final String title;
  final String subtitle;
  final IconData icon;

  const LegalDoc({
    required this.slug,
    required this.title,
    required this.subtitle,
    required this.icon,
  });

  /// Bundled fragment path rendered by [LegalDocumentPage].
  String get assetPath => 'assets/legal/$slug.html';

  /// Canonical public URL (used for "open on web" / sharing if ever needed).
  String get webUrl => 'https://amril.app/legal/$slug';
}

/// The full set, in the order shown in the Legal & Policies hub.
/// NOTE: cookies / acceptable-use / coins / vendor-agreement assets are added
/// in the next legal batch; their tiles are listed here already so the hub is
/// complete the moment those fragments land in assets/legal/.
const List<LegalDoc> kLegalDocs = [
  LegalDoc(
    slug: 'privacy',
    title: 'Privacy Policy',
    subtitle: 'What we collect and how we protect it',
    icon: Icons.privacy_tip_outlined,
  ),
  LegalDoc(
    slug: 'terms',
    title: 'Terms of Service',
    subtitle: 'The agreement for using Amril',
    icon: Icons.description_outlined,
  ),
  LegalDoc(
    slug: 'cookies',
    title: 'Cookie Policy',
    subtitle: 'Cookies and similar technologies',
    icon: Icons.cookie_outlined,
  ),
  LegalDoc(
    slug: 'acceptable-use',
    title: 'Community Guidelines',
    subtitle: 'What is and isn\'t allowed on Amril',
    icon: Icons.shield_outlined,
  ),
  LegalDoc(
    slug: 'coins',
    title: 'Coins & Gifting Terms',
    subtitle: 'How coins, gifts, and conversions work',
    icon: Icons.toll_outlined,
  ),
  LegalDoc(
    slug: 'vendor-agreement',
    title: 'Vendor Agreement',
    subtitle: 'For businesses selling on Amril',
    icon: Icons.storefront_outlined,
  ),
];

/// Convenience lookups used by Settings tiles that point at a specific doc.
LegalDoc legalDocBySlug(String slug) =>
    kLegalDocs.firstWhere((d) => d.slug == slug);